name: CI - FastVision
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'FastTabular/**'
      - 'FastText/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'FastTabular/**'
      - 'FastText/**'
      - '*.md'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
        
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Dev FastAI
        run: |
          julia --color=yes --project=./FastVision -e "using Pkg; Pkg.develop([Pkg.PackageSpec(path=\"./\")])"
      - name: Dev test dependenceis
        run: |
          julia --color=yes --project=./FastVision -e "using Pkg; Pkg.develop([Pkg.PackageSpec(path=\"./\"), Pkg.PackageSpec(path=\"./FastMakie/\")])"
      - uses: julia-actions/julia-buildpkg@latest
        with:
          project: './FastVision/'
      - uses: julia-actions/julia-runtest@latest
        with:
          project: './FastVision/'
        continue-on-error: ${{ matrix.version == 'nightly' }}
